import { Geist, Geist_Mono, Great_Vibes } from "next/font/google";
import "./globals.css";
import { SessionProvider, useSession } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import Script from "next/script";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import DashBoardSideBar from "@/components/DashBoardSideBar";
import Providers from "./providers";
import { getCart } from "./action/addToCart";
import { auth } from "@/lib/auth";
import { CartContext } from "./context/CartContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// const greatVibes = Great_Vibes({
//   weight: "400",
//   subsets: ["latin"],
//   variable: "--font-great-vibes",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const authResult = await auth();
  const user = authResult?.user;
  console.log("data in layout", user?.id);
  const cart = await getCart(user?.id);
  console.log("cart in layout", cart);
  return (
    <html lang="en">
      <head>
        <Script src="https://checkout.razorpay.com/v1/checkout.js"></Script>
        <link
          href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="antialiased bg-background text-foreground transition-colors duration-300">
        <Providers>
          <SessionProvider>
            <CartContext initialCart={cart.cart}>
              <Toaster />
              {children}
            </CartContext>
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
